version: '3.8'

services:
  postgres:
    extends:
      file: service.yml
      service: postgres
    networks:
      - to-do-list

  pgadmin:
    extends:
      file: service.yml
      service: pgadmin
    networks:
      - to-do-list
    depends_on:
      - postgres

  rabbitmq:
    extends:
      file: service.yml
      service: rabbitmq
    networks:
      - to-do-list

  to-do-list-app:
    extends:
      file: service.yml
      service: to-do-list-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?prepareThreshold=0
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SHOW_SQL: ${SHOW_SQL}
      LOGGING_LEVEL_SEC: ${LOGGING_LEVEL_SEC}
      LOGGING_LEVEL_ROOT: ${LOGGING_LEVEL_ROOT}
      LOGGING_LEVEL_KYZIA: ${LOGGING_LEVEL_KYZIA}
    networks:
      - to-do-list
    depends_on:
      - postgres

networks:
  to-do-list: